Interview fields were validate
swnat/peoplemanagement pull request #20
Opened 2020-02-14 14:31 UTC by mariebenitez

## Description

Interview fields were validated so that only characters can be entered, the validated fields are comment and add participant.
## Motivation and Context

Solves problem validation of comment fields and add participant.

## How Has This Been Tested?

Has been tested manually

### Do you have any tests?
- [ ] Yes
- [X ] No

2020-02-17 20:11 UTC, rodrigovelazq submitted a review, later dismissed

2020-02-18 13:59 UTC, sofiarivas93 requested changes
Comments should be less restricted.

2020-02-18 14:49 UTC, joseiba commented
> Los comentarios deben ser menos restringidos.

2020-02-18 14:52 UTC, joseiba commented
> Comments should be less restricted.

It was added again that the comment field can contain numbers, the only change is that you can not add numbers as participants in an interview only names.

2020-02-18 20:28 UTC, sofiarivas93 approved these changes

2020-02-18 20:46 UTC, rodrigovelazq approved these changes

2020-02-18 20:46 UTC, merged