Add candidate profile photo
swnat/peoplemanagement pull request #22
Opened 2020-02-20 12:43 UTC by veraivan

## Description

A new functionality was added, when creating a new candidate you have the possibility to attach a photo for your profile.

## Motivation and Context

The fact that a candidate can add their photo, improves the visualization for other users and also in terms of the visual is achieved much more striking.

## How Has This Been Tested?

A new test has been added that tests if the default image is loaded when you want to add a new candidate, (when a candidate does not add their photo).  

### Do you have any tests?
- [x] Yes
- [ ] No

2020-02-20 13:52 UTC, rodrigovelazq requested changes
The image is deleted when a profile field is modified. 
Steps:
1. Create a profile with a photo.
2. Go to the list of candidates.
3. Enter the previously created profile.
4. Modify any field and save.
5. Go to the list of candidates.
6. Return to the saved profile.

2020-02-20 14:49 UTC, veraivan commented
> The image is deleted when a profile field is modified.
> Steps:
> 
> 1. Create a profile with a photo.
> 2. Go to the list of candidates.
> 3. Enter the previously created profile.
> 4. Modify any field and save.
> 5. Go to the list of candidates.
> 6. Return to the saved profile.

Solved the image loading when editing.

2020-02-21 14:27 UTC, rodrigovelazq approved these changes

2020-02-21 14:29 UTC, sofiarivas93 approved these changes

2020-02-21 14:29 UTC, merged